stages:
  - build
  - test
  - deploy

variables:
  GO_VERSION: '1.24.0'

build:
  stage: build
  image: golang:1.24.0-alpine
  script:
    - go mod download
    - go build -v ./...
  artifacts:
    paths:
      - "*.exe"
      - "*.bin"
    expire_in: 1 hour

test:
  stage: test
  image: golang:1.24.0-alpine
  script:
    - go mod download
    - go test -v -race -coverprofile=coverage.out ./...
    - go tool cover -html=coverage.out -o coverage.html
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.out
      - coverage.html
    expire_in: 1 week
  coverage: '/coverage: \d+\.\d+%/'

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying application"
  only:
    - main
    - master
