name: Go CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  GO_VERSION: '1.24.3'
  MAIN_PACKAGE_PATH: 'main.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24.3'
    - name: Build
      run: go build -o bin/app ${{ env.MAIN_PACKAGE_PATH }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-binary
        path: bin/app