name: Go CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env: 
	GO_VERSION: '1.23.6' 

jobs:
  build:
    runs-on: ubuntu-latest
		steps:
    	- uses: actions/checkout@v3
    	- name: Set up Go
     	  uses: actions/setup-go@v3
		  with:
			  go-version: '1.23.6' 
    - name: Build
      run: go build -o bin/app main.go
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-binary
        path: bin/app