name: Go CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env: 
	GO_VERSION: '1.23.6' 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Download dependencies
      run: go get .
    
    - name: Run tests
      run: go test -v ./...
    - name: Build
      run: go build -v ./...
    - name: Security scan
      run: go vet ./...
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
    - name: Build
      run: go build -o bin/app main.go
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-binary
        path: bin/app