name: .NET CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  setup:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
  restore:
    runs-on: windows-latest
    needs: setup
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    - name: Restore dependencies
      run: dotnet restore
  test:
    runs-on: windows-latest
    needs: restore
    strategy:
      matrix:
        dotnet: [ '7.0.x', '8.0.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --logger trx
  publish:
    runs-on: windows-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack (NuGet)
      run: dotnet pack --no-build --configuration Release -o packages
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: packages/
